### ISSUE TITLE
DataAugmentVOC.py文件中第161行报错

### ISSUE THREAD

**Issue by Ty112358** [Mygithub-Yao/tools-VOC#2]
感谢作者分享，在DataAugmentVOC.py文件161行会报错，所调用函数中并无foder_name这一个参数，把这一行删掉即可

**Comment by WenyaoL** [comment]
> 感谢作者分享，在DataAugmentVOC.py文件161行会报错，所调用函数中并无foder_name这一个参数，把这一行删掉即可

感谢提醒，bug已经修复!

**Comment by WenyaoL** [comment]
问题已解决
