### ISSUE TITLE
亮度变换xml对应不上

### ISSUE THREAD

**Issue by QHdsj1** [Mygithub-Yao/tools-VOC#5]
调整亮度的数据增强xml完全对应不上

**Comment by WenyaoL** [comment]
哪里对应不上，文件名还是xml里面的内容，方便具体说一下吗，这可以让我快速定位到BUG

**Comment by QHdsj1** [comment]
增强后框的坐标对应不上

**Comment by WenyaoL** [comment]
经过测试，我这边并没有出现你这边的情况（因为修改亮度的代码并没有进行坐标的修改，所以应该不会出现坐标移动的问题）
以我猜测问题出现的原因有以下几种：
1. 增强前，图片和xml名字没有一 一 对应   
2. 没有清洗掉多余的xml文件或者多余的图片（即：清洗掉没有打标签的图片，清洗掉没有对应图片的xml文件）
我判断大概率是问题2，因为我的代码逻辑如下（分两个线程处理）：
线程一：遍历图片文件夹，对图片进行亮度修改，然后进行保存。（所以图片的排序是根据你文件下图片文件的默认排序的）
线程二：遍历xml文件夹，对原xml文件进行复制并重命名，然后保存。（xml文件的排序是根据你文件夹下xml文件的默认排序）

**Comment by WenyaoL** [comment]
如果你需要进行简单的清洗，可以使用tools-VOC/DateAugmentLabelImg/tools/下的脚本进行简易的清洗
清洗前请确保数据备份（因为涉及到文件的删除操作）

**Comment by WenyaoL** [comment]
问题已解决
