### ISSUE TITLE
rotate之后，标签不正确

### ISSUE THREAD

**Issue by hongzhifenghahaha** [Mygithub-Yao/tools-VOC#6]
如下两图，图一是原本的图和标签，图二是旋转45度后的图和标签，可以看到，旋转之后所打的标签的左下角那个点并不能覆盖原本的坦克模型

![src](https://user-images.githubusercontent.com/58628147/128313810-d00d1214-8178-49be-bb3b-4a823f742d80.png)

![45_rotation](https://user-images.githubusercontent.com/58628147/128313828-7bc05340-f2ce-45cd-ab07-e169548cef88.png)

作者有空的时候可以看一下这个bug，我怀疑是图片旋转后被缩放导致坐标计算错误。

**Comment by WenyaoL** [comment]
其实我计算时是有考虑缩放问题的，坐标计算错误主要是涉及到物体自身形状的问题，有些物体是有邻角的，在对源坐标进行转换后，并不能确保完全覆盖掉物体的邻角，其实这个问题我也十分头疼。
我查了些资料，找到了一些方法对问题进行修补，可以通过对坐标轴在转换之前做些修正，修正代码如下（我修改前的代码使用的是第三种发生）：

其实问题是出现在**tools-VOC/DateAugmentLabelImg/LabelParser.py**下的116~129行之间的代码，网上资料普片使用第三种，我也见人使用第一种的，不过根据我的对比，我取了两者之间修改，你可以更改下面代码中的除数4（当数值为2时，效果等于第三种，取无限大时等于第一种效果）。

```
            # point1 = np.dot(rot_mat, np.array([xmin, ymin, 1]))          #这种新画出的框大一圈（网上也有人用）
            # point2 = np.dot(rot_mat, np.array([xmax, ymin, 1]))
            # point3 = np.dot(rot_mat, np.array([xmax, ymax, 1]))
            # point4 = np.dot(rot_mat, np.array([xmin, ymax, 1]))

            point1 = np.dot(rot_mat, np.array([xmin + (xmax-xmin) / 4, ymin, 1]))  # 去两者之间（可以根据实际情况修改里面的4）
            point2 = np.dot(rot_mat, np.array([xmax, ymin + (ymax-ymin) / 4, 1]))  #修改范围为2~max大
            point3 = np.dot(rot_mat, np.array([xmax - (xmax-xmin) / 4, ymax, 1]))
            point4 = np.dot(rot_mat, np.array([xmin, ymax - (ymax-ymin) / 4, 1]))

            # point1 = np.dot(rot_mat, np.array([(xmin + xmax) / 2, ymin, 1]))  # 获取原始矩形的四个中点，然后将这四个点转换到旋转后的坐标系下
            # point2 = np.dot(rot_mat, np.array([xmax, (ymin + ymax) / 2, 1]))  #这种会紧凑很多，不过网上大部分实现都是这种
            # point3 = np.dot(rot_mat, np.array([(xmin + xmax) / 2, ymax, 1]))
            # point4 = np.dot(rot_mat, np.array([xmin, (ymin + ymax) / 2, 1]))
```

**Comment by hongzhifenghahaha** [comment]
作者你好，刚测试了一下你提供的其他两种方法，发现确实是物体自身形状导致的问题。

有些物体旋转后，采用紧凑的那种写法是没有问题的。
而有些物体旋转后，采用紧凑的写法就无法完全覆盖，但采用更大一圈的框又会过大。

目前看来好像确实无法很完美的解决，我也只能是先自动标注一下旋转后的数据，然后再自己手动微调了
