### ISSUE TITLE
change_Annotations不完整

### ISSUE THREAD

**Issue by ratchips** [Mygithub-Yao/tools-VOC#8]
Annotations中有881个xml文件，在执行了

`python Augment_script.py --root=./TestData/VOC --filp=True
`
之后，change_Annotations只有671，第一行进度条是671/881

**Comment by WenyaoL** [comment]
删除没打标签的图片，或者删除没图片的标签，并确保标签名和图片名对应。（严格确保一一对应）
当初写代码的时候分开了两个线程去处理，代码设计有些问题，现在项目也不打算大更新了。

**Comment by WenyaoL** [comment]
可以用tools-VOC/DateAugmentLabelImg/tools/下的代码做简易的清理
